name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  verificar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.20.4'
          otp-version: '29.0'
          
      - name: Instalar dependencias
        run: mix deps.get
        
      - name: Compilar proyecto
        run: mix compile --warnings-as-errors
        
      - name: Análisis de formato (opcional)
        run: mix format --check-formatted
        
      - name: Pruebas
        run: mix test